spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zabbix
    url: jdbc:mysql://10.10.148.9:3306/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 10.10.148.10
    port: 5672
    username: guest
    password: guest      
  redis:
    host: 10.10.148.9
    port: 6379
env:
  dev4
girl:
  name: wangxh
  age: 26 
