spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234
    url: jdbc:mysql://10.10.148.9:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 10.10.148.10
    port: 5672
    username: guest
    password: guest
  redis:
    host: 10.10.148.9
    port: 6379
